/* eslint-disable */
/**
 * Stub for testing — the real version is generated by `npx convex dev`.
 * Uses anyApi (a Proxy) so all function references resolve dynamically,
 * matching how the main project's generated api.js works.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
