/* eslint-disable */
/**
 * Stub for testing — the real version is generated by `npx convex dev`.
 * Re-exports generic builders from convex/server; convex-test replaces
 * these at runtime with its own mock implementations.
 */
export {
  queryGeneric as query,
  mutationGeneric as mutation,
  actionGeneric as action,
  internalQueryGeneric as internalQuery,
  internalMutationGeneric as internalMutation,
  internalActionGeneric as internalAction,
  httpActionGeneric as httpAction,
} from "convex/server";
